site_name: DermAlert Backend
site_description: Sistema backend para diagnóstico dermatológico com IA
site_author: Giovanni
repo_url: https://github.com/DermAlert/dermalert-backend
repo_name: dermalert-backend

theme:
  name: material
  language: pt
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Configuração:
    - PostgreSQL: setup/postgres.md
    - MinIO: setup/minio.md
    - Ambiente de Desenvolvimento: setup/development.md
  - Seeds:
    - Guia Rápido: seeds/quick-guide.md
    - Documentação Completa: seeds/complete-guide.md
    - Resumo Técnico: seeds/technical-summary.md
    - Commands Reference: seeds/commands-reference.md
  - API:
    - Accounts: api/accounts.md
    - Health Units: api/health-units.md
    - Endereços: api/addresses.md
  - Desenvolvimento:
    - Arquitetura: development/architecture.md
    - Testes: development/testing.md
    - Deploy: development/deploy.md

plugins:
  - search:
      lang: pt
