# Generated by Django 5.2 on 2025-09-01 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile_forms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cancerresearch",
            name="doctor_assistance",
        ),
    ]
