# Generated by Django 5.2 on 2025-08-26 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_forms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskProtectiveFactors",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "sun_exposure_period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("few_times_per_week", "A few times per week"),
                            ("occasionally", "Occasionally"),
                            ("no_exposure", "Does not expose to the sun"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "sun_burn",
                    models.CharField(
                        choices=[
                            ("once_twice", "1-2 times"),
                            ("three_to_five", "3-5 times"),
                            ("more_than_five", "More than 5 times"),
                            ("never", "Never had"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "uv_protection",
                    models.CharField(
                        choices=[
                            ("none", "Does not use"),
                            ("spf_15", "SPF 15"),
                            ("spf_30", "SPF 30"),
                            ("spf_50", "SPF 50"),
                            ("spf_70", "SPF 70"),
                            ("spf_100_plus", "SPF 100 or more"),
                        ],
                        max_length=40,
                    ),
                ),
                ("hat_use", models.BooleanField(default=False)),
                ("artifitial_tan", models.BooleanField(default=False)),
                (
                    "checkups_frequency",
                    models.CharField(
                        choices=[
                            ("annually", "Annually"),
                            ("every_six_months", "Every 6 months"),
                            ("not_regularly", "Not regularly"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("cancer_campaigns", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_protective_factors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
