# Generated by Django 5.2 on 2025-10-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_forms', '0002_remove_cancerresearch_doctor_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhistory',
            name='removed_injuries',
            field=models.BooleanField(default=False),
        ),
    ]
