# Generated by Django 5.2 on 2025-08-26 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_forms", "0003_cancerresearch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "hypertension",
                    models.CharField(
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("DONT_KNOW", "Don't know"),
                        ],
                        default="NO",
                        max_length=20,
                    ),
                ),
                (
                    "diabetes",
                    models.CharField(
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("DONT_KNOW", "Don't know"),
                        ],
                        default="NO",
                        max_length=20,
                    ),
                ),
                (
                    "deep_vein_thrombosis",
                    models.CharField(
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("DONT_KNOW", "Don't know"),
                        ],
                        default="NO",
                        max_length=20,
                    ),
                ),
                (
                    "chronic_venous_insufficiency",
                    models.CharField(
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("DONT_KNOW", "Don't know"),
                        ],
                        default="NO",
                        max_length=20,
                    ),
                ),
                (
                    "compression_stockings_use",
                    models.CharField(
                        choices=[
                            ("CURRENTLY", "Yes, currently"),
                            ("USED_BUT_NOT_ANYMORE", "Yes, but not anymore"),
                            ("NEVER_USED", "Never used"),
                            ("DONT_KNOW_WHAT_IT_IS", "Doesn't know what it is"),
                        ],
                        default="NEVER_USED",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
