# Generated by Django 5.2 on 2025-08-26 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_forms", "0004_clinicalhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifestyleRisk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "long_periods_posture",
                    models.CharField(
                        choices=[
                            ("STANDING_LONG_HOURS", "Yes, standing for many hours"),
                            ("SITTING_LONG_HOURS", "Yes, sitting for many hours"),
                            ("NO", "No"),
                        ],
                        default="NO",
                        max_length=30,
                    ),
                ),
                (
                    "leg_foot_trauma",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default="NO",
                        max_length=5,
                    ),
                ),
                (
                    "smoking",
                    models.CharField(
                        choices=[
                            ("CURRENT_SMOKER", "Yes, currently"),
                            ("FORMER_SMOKER", "I used to smoke, but quit"),
                            ("NEVER_SMOKED", "Never smoked"),
                        ],
                        default="NEVER_SMOKED",
                        max_length=20,
                    ),
                ),
                (
                    "physical_activity",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default="NO",
                        max_length=5,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifestyle_risk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
