# Generated by Django 5.2 on 2025-08-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_forms', '0007_careaccesssupport_currentulcerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancerresearch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='careaccesssupport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='currentulcerinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='familyvascularhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='generalhealth',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lifestylerisk',
            name='description',
        ),
        migrations.RemoveField(
            model_name='phototype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='riskprotectivefactors',
            name='description',
        ),
    ]
