# Generated by Django 5.2 on 2025-08-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_forms', '0008_remove_cancerresearch_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhistory',
            name='removed_injuries',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='patient_cancer_type',
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='patient_cancer_type',
            field=models.ManyToManyField(blank=True, related_name='patient_forms', to='profile_forms.cancertypes'),
        ),
    ]
