# Generated by Codex on 2026-03-18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions.text import Lower


def normalize_legacy_work_assignments(apps, schema_editor):
    Work = apps.get_model("accounts", "Work")

    duplicate_assignments = (
        Work.objects.filter(is_active=True, is_deleted=False)
        .values("user_id", "health_unit_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )
    for duplicate in duplicate_assignments:
        rows = list(
            Work.objects.filter(
                user_id=duplicate["user_id"],
                health_unit_id=duplicate["health_unit_id"],
                is_active=True,
                is_deleted=False,
            ).order_by("-updated_at", "-created_at", "-id")
        )
        for stale_row in rows[1:]:
            stale_row.is_active = False
            stale_row.is_deleted = True
            stale_row.save(update_fields=["is_active", "is_deleted"])

    duplicate_supervisors = (
        Work.objects.filter(
            permission_role="supervisor",
            is_active=True,
            is_deleted=False,
        )
        .values("user_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )
    for duplicate in duplicate_supervisors:
        rows = list(
            Work.objects.filter(
                user_id=duplicate["user_id"],
                permission_role="supervisor",
                is_active=True,
                is_deleted=False,
            ).order_by("-updated_at", "-created_at", "-id")
        )
        for stale_row in rows[1:]:
            stale_row.is_active = False
            stale_row.is_deleted = True
            stale_row.save(update_fields=["is_active", "is_deleted"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("hash", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permission_role",
                    models.CharField(
                        choices=[
                            ("supervisor", "Supervisor"),
                            ("technician", "Technician"),
                        ],
                        default="technician",
                        max_length=15,
                        verbose_name="Permission Role",
                    ),
                ),
                ("start_date_work", models.DateTimeField(blank=True, null=True)),
                ("end_date_work", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_unit_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_codes",
                        to="health_unit.healthunit",
                        verbose_name="Health Unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_works",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invite Code",
                "verbose_name_plural": "Invite Codes",
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="health_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="health_unit.healthunit",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RunPython(
            normalize_legacy_work_assignments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                Lower("email"),
                condition=~models.Q(email=""),
                name="accounts_user_unique_email_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="work",
            constraint=models.UniqueConstraint(
                fields=("user", "health_unit"),
                condition=models.Q(is_active=True, is_deleted=False),
                name="accounts_work_unique_active_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="work",
            constraint=models.UniqueConstraint(
                fields=("user",),
                condition=models.Q(
                    permission_role="supervisor",
                    is_active=True,
                    is_deleted=False,
                ),
                name="accounts_work_unique_active_supervisor",
            ),
        ),
    ]
