# Generated by Django 5.2 on 2025-07-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_patient_other_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'A user with that cpf already exists.'}, help_text='', max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
