# Generated by Django 5.2 on 2025-08-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sus_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'A user with that cpf already exists.'}, help_text='', max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
