# Generated by Django 5.2 on 2025-08-26 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head_neck.scalp", "Scalp"),
                            ("head_neck.face", "Face"),
                            ("head_neck.neck", "Neck"),
                            ("trunk.chest_front", "Chest (anterior)"),
                            ("trunk.chest_back", "Chest (posterior)"),
                            ("trunk.upper_abdomen", "Upper abdomen"),
                            ("trunk.lower_abdomen", "Lower abdomen"),
                            ("trunk.back", "Back"),
                            ("trunk.flanks", "Flanks"),
                            ("pelvis.pubis", "Pubis"),
                            ("pelvis.genitals", "Genitals"),
                            ("pelvis.buttocks", "Buttocks"),
                            ("pelvis.coccyx", "Coccyx"),
                            ("extremities.shoulder", "Shoulder"),
                            ("extremities.arm", "Arm"),
                            ("extremities.forearm", "Forearm"),
                            ("extremities.hand", "Hand"),
                            ("extremities.thigh", "Thigh"),
                            ("extremities.leg", "Leg"),
                            ("extremities.foot", "Foot"),
                        ],
                        max_length=128,
                        verbose_name="Body Site",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skin_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
