# Generated by Django 5.2 on 2025-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincondition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
