# Generated by Django 5.2 on 2025-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_conditions', '0003_remove_skincondition_description_skincondition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincondition',
            name='location',
            field=models.CharField(choices=[('head_neck.scalp', 'Scalp'), ('head_neck.forehead', 'Forehead'), ('head_neck.eyes', 'Eyes'), ('head_neck.nose', 'Nose'), ('head_neck.mouth', 'Mouth'), ('head_neck.ears', 'Ears'), ('head_neck.face', 'Face'), ('head_neck.neck', 'Neck'), ('trunk.chest_front', 'Chest (anterior)'), ('trunk.chest_back', 'Chest (posterior)'), ('trunk.upper_abdomen', 'Upper abdomen'), ('trunk.lower_abdomen', 'Lower abdomen'), ('trunk.back', 'Back'), ('trunk.flanks', 'Flanks'), ('pelvis.pubis', 'Pubis'), ('pelvis.genitals', 'Genitals'), ('pelvis.buttocks', 'Buttocks'), ('pelvis.coccyx', 'Coccyx'), ('extremities.shoulder_right', 'Right shoulder'), ('extremities.shoulder_left', 'Left shoulder'), ('extremities.arm_right', 'Right arm'), ('extremities.arm_left', 'Left arm'), ('extremities.forearm_right', 'Right forearm'), ('extremities.forearm_left', 'Left forearm'), ('extremities.hand_right', 'Right hand'), ('extremities.hand_left', 'Left hand'), ('extremities.thigh_right', 'Right thigh'), ('extremities.thigh_left', 'Left thigh'), ('extremities.leg_right', 'Right leg'), ('extremities.leg_left', 'Left leg'), ('extremities.foot_right', 'Right foot'), ('extremities.foot_left', 'Left foot')], max_length=128, verbose_name='Body Site'),
        ),
    ]
