from .wound import SkinConditionWoundNestedViewSet
from .wound_image import WoundImageNestedViewSet
from .cancer import SkinConditionCancerNestedViewSet
from .cancer_image import CancerImageNestedViewSet
