# Generated by Django 5.2 on 2025-08-30 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skin_conditions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('height_mm', models.IntegerField()),
                ('width_mm', models.IntegerField()),
                ('depth_injury', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cancer',
                'verbose_name_plural': 'Cancers',
                'indexes': [models.Index(fields=['id'], name='skin_forms__id_4c6338_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField()),
                ('width_mm', models.PositiveIntegerField()),
                ('wound_edges', models.CharField(choices=[('no_edges', 'Ausência de bordos da ferida'), ('diffuse', 'Difusos'), ('well_defined', 'Delimitados'), ('damaged', 'Danificados'), ('thickened', 'Espessados (“envelhecidos”, “evertidos”)')], default='no_edges', max_length=50)),
                ('wound_bed_tissue', models.CharField(choices=[('regenerated_scarred', 'Tecido regenerado ou cicatrizado'), ('epithelialization', 'Tecido de epitelização'), ('granulation', 'Tecido de granulação'), ('devitalized_fibrinous', 'Tecido desvitalizado e/ou fibrinoso'), ('necrotic', 'Tecido necrosado (necrose seca ou úmida)')], default='regenerated_scarred', max_length=50)),
                ('depth_of_tissue_injury', models.CharField(choices=[('intact_skin', 'Pele intacta ou cicatrizada'), ('epidermis_dermis', 'Atingimento de epiderme e derme'), ('hypodermis_subcutaneous', 'Atingimento de hipoderme ou tela subcutânea (tecido adiposo sem atingir fáscia muscular)'), ('muscle_tissue', 'Atingimento de tecido muscular'), ('bone_tissue', 'Atingimento de tecido ósseo e/ou tecidos anexos (tendões, ligamentos, cápsula articular) ou necrose negra')], default='intact_skin', max_length=50)),
                ('exudate_type', models.CharField(choices=[('dry', 'Seco'), ('moist', 'Úmido'), ('wet', 'Molhado'), ('saturated', 'Saturado'), ('leakage', 'Com fuga de exsudato')], default='dry', max_length=50)),
                ('increased_pain', models.BooleanField(default=False)),
                ('perilesional_erythema', models.BooleanField(default=False)),
                ('perilesional_edema', models.BooleanField(default=False)),
                ('heat_or_warm_skin', models.BooleanField(default=False)),
                ('increased_exudate', models.BooleanField(default=False)),
                ('purulent_exudate', models.BooleanField(default=False)),
                ('friable_tissue', models.BooleanField(default=False)),
                ('stagnant_wound', models.BooleanField(default=False)),
                ('biofilm_compatible_tissue', models.BooleanField(default=False)),
                ('odor', models.BooleanField(default=False)),
                ('hypergranulation', models.BooleanField(default=False)),
                ('wound_size_increase', models.BooleanField(default=False)),
                ('satallite_lesions', models.BooleanField(default=False)),
                ('grayish_wound_bed', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('skin_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wounds', to='skin_conditions.skincondition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wound',
                'verbose_name_plural': 'Wounds',
                'indexes': [models.Index(fields=['id'], name='skin_forms__id_3d260f_idx'), models.Index(fields=['skin_condition'], name='skin_forms__skin_co_4f9085_idx')],
            },
        ),
    ]
